/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        xs: "320px",
        mobileMedium: "375px",
        xm: "500px",
        tablet: "660px",
        tabletLarge: "700px",
        pdt: "849px",
        laptop: "970px",
        laptopLarge: "1024px",
        desktop: "1200px",
        desktopMedium: "1400px",
        desktopLarge: "1920px",
      },
      fontFamily: {
        "monrope-regular": ["Manrope-Regular", "sans-serif"],
        "monrope-medium": ["Manrope-Medium", "sans-serif"],
        "monrope-semiBold": ["Manrope-SemiBold", "sans-serif"],
        "spectral-medium": ["Spectral-Medium", "sans-serif"],
        "spectral-mediumItalic": ["Spectral-MediumItalic", "sans-serif"],
        testimonia: ["Testimonia", "sans-serif"],
      },
      spacing: {
        "max-width": "1400px",
      },
      colors: {
        white: "#ffffff",
        textMain: "#616161",
        accent: "#D6A07E",
        accentBg: "#f3ede8",
        textSubTitle: "#6F6D6C",
        accentSecondary: "#828282",
        whiteBtn: "rgba(255, 255, 255, 0.15)",
        yellowBg: "#F6F1DC",
        borderBtn: "#E1DCC6",
        blue: "#CCDBDE",
        blueBg: "#f4f7f8",
        border: "rgba(235, 235, 234, 0.5)",
        greyLight: "#9D9C9C",
        grayBg: "#e3e3e1",
        pink: "#E8D3D7",
        pinkBg: "#fcf8f9",
        langBg: "rgba(255, 255, 255, 0.15)",
        langBgHover: "bg-rgba(255, 255, 255, 0.8)",
      },
      gridTemplateColumns: {
        mobile: "repeat(4, 1fr)",
        tablet: "repeat(12, 1fr)",
        desktop: "repeat(12, 98px)",
      },
      gap: {
        "col-gap": "20px",
      },
      gridColumn: {
        "span-1": "span 1 / span 1",
        "span-2": "span 2 / span 2",
        "span-3": "span 3 / span 3",
        "span-4": "span 4 / span 4",
        "span-5": "span 5 / span 5",
        "span-6": "span 6 / span 6",
        "span-7": "span 7 / span 7",
        "span-8": "span 8 / span 8",
        "span-9": "span 9 / span 9",
        "span-10": "span 10 / span 10",
        "span-11": "span 11 / span 11",
        "span-12": "span 12 / span 12",
      },
      gridColumnStart: {
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
      },
      gridColumnEnd: {
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
      },
      transitionDuration: {
        custom: "300ms",
      },
      opacity: {
        0: "0",
        100: "1",
      },
      objectPosition: {
        "top-10": "10% top",
        "top-20": "20% top",
        "top-30": "30% top",
        "top-40": "40% top",
        "top-50": "50% top",
        "bottom-10": "10% bottom",
        "bottom-20": "20% bottom",
        "bottom-30": "30% bottom",
        "bottom-40": "40% bottom",
        "bottom-50": "50% bottom",
        "left-10": "left 10%",
        "left-20": "left 20%",
        "left-30": "left 30%",
        "left-40": "left 40%",
        "left-50": "left 50%",
        "right-10": "right 10%",
        "right-20": "right 20%",
        "right-30": "right 30%",
        "right-40": "right 40%",
        "right-50": "right 50%",
      },
    },
  },
  plugins: [],
};
